steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/exemplary-cycle-352007/nexthotel-modeldeployment:$COMMIT_SHA",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "gcr.io/exemplary-cycle-352007/nexthotel-modeldeployment:$COMMIT_SHA",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "nexthotel-modeldeployment",
        "--region=asia-southeast1",
        "--image=gcr.io/exemplary-cycle-352007/nexthotel-modeldeployment:$COMMIT_SHA",
      ]
